version: "3.4"

services:
  cockroach:
    image: <url to the image>
    command: "start --insecure"
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    environment:
      SNAME: "{{.Service.Name}}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 120s
        order: stop-first
    networks:
    - cockroach-network
    volumes:
    - "cockroach_data:/cockroach/cockroach-data"
    ports:
    - "8080:8080"
    - "26257:26257"

networks:
  cockroach-network:
    driver: overlay

volumes:
  cockroach_data:
    name: '{{.Service.Name}}_DataVol-{{.Task.Slot}}'
